import json,re
d=json.load(open('../jb_batch2.json',encoding='utf-8'))
items={x['ref']:x for x in d}
E={}
def ok(ref,e): E[ref]={"verdict":"ok","explanation":e}
def fix(ref,e,stem=None,options=None):
    x=items[ref]
    s=stem if stem is not None else x['stem']
    o=dict(options if options is not None else x['options'])
    s=s.replace(r'\textbf{List-I}','List-I').replace(r'\textbf{List-II}','List-II')
    s=re.sub(r'\n\s*\n+','\n',s).strip()
    for k in o:
        v=o[k]
        if '\\quad' in v:
            pairs=re.findall(r'\(([PQRS])\)\s*\$?\s*\\rightarrow\s*\$?\s*\((\d)\)',v)
            if len(pairs)==4:
                v='; '.join(r'$(%s) \rightarrow (%s)$'%p for p in pairs)
            else:
                v=v.replace(r'$\quad$','').strip()
        v=v.rstrip(',').rstrip('.').strip()
        o[k]=v
    E[ref]={"verdict":"fix","explanation":e,"stem":s,"options":o}
P="JEE Adv "
ok(P+"2021 Paper 2 Q33",r"$\mathrm{K_4[Fe(CN)_6]}$ supplies $\mathrm{[Fe(CN)_6]^{4-}}$ and $\mathrm{FeSO_4}$ supplies $\mathrm{Fe^{2+}}$; with no air, all iron stays +2, giving the white precipitate $\mathrm{K_2Fe[Fe(CN)_6]}$. In air, $\mathrm{Fe^{2+}}$ is oxidised and it turns into Prussian blue. Trap: $\mathrm{Fe_4[Fe(CN)_6]_3}$ is the blue product (Prussian/Turnbull's blue), not the white one.")
ok(P+"2021 Paper 2 Q49",r"$S_{n-1}=2-2^{2-n}$, so the farthest point of $C_n$ is at $S_{n-1}+a_n=2-2^{1-n}$. This is $\le r=2-\frac{1}{513}$ when $2^{n-1}\le 513$, i.e. $n\le 10$, so $k=10$. Consecutive circles intersect (centre distance $a_n<a_n+a_{n+1}$), but $C_n,C_{n+2}$ are disjoint ($1.5a_n>1.25a_n$), so take alternate circles: $l=5$. Hence $3k+2l=40$.")
ok(P+"2022 Paper 1 Q15",r"(I) $\sin(x+\pi/4)=1/\sqrt2$ gives $x=0,\pi/2$: two elements. (II) $\tan3x=1/\sqrt3$ gives $x=\pi/18+n\pi/3$; only $\pi/18,-5\pi/18$ lie in range: two. (III) $\cos2x=\sqrt3/2$ gives $x=\pm\pi/12+n\pi$: $\pm\pi/12,\pm11\pi/12,\pm13\pi/12$, six. (IV) $\sin(x-\pi/4)=1/\sqrt2$ gives $x=\pi/2+2n\pi$ or $\pi+2n\pi$: $\pi/2,-3\pi/2,\pm\pi$, four. So I-P, II-P, III-T, IV-R. Trap: endpoints such as $-5\pi/18$ are included.")
ok(P+"2022 Paper 1 Q16",r"Each round, $X-Y$ changes by $+5,0,-5$ with probabilities $\frac5{12},\frac16,\frac5{12}$. $P(X_2>Y_2)=(\frac5{12})^2+2\cdot\frac5{12}\cdot\frac16=\frac{45}{144}=\frac5{16}$, so $P(X_2\ge Y_2)=1-\frac5{16}=\frac{11}{16}$ by symmetry. $P(X_3=Y_3)=(\frac16)^3+6\cdot\frac{25}{144}\cdot\frac16=\frac{77}{432}$, and $P(X_3>Y_3)=\frac12(1-\frac{77}{432})=\frac{355}{864}$. So I-Q, II-R, III-T, IV-S.")
fix(P+"2022 Paper 1 Q18",r"With $F=(2\cos\phi,2\sin\phi)$, $\alpha=2\cos\phi$. The tangent at $E$ is $\frac{\alpha x}{4}+\frac{y y_E}{3}=1$, which meets the $x$-axis at $G=(4/\alpha,0)$. Area $=\frac12(\frac4\alpha-\alpha)\cdot2\sin\phi=2\sin^2\phi\tan\phi$. $\phi=\pi/4$ gives $1$, $\pi/3$ gives $\frac{3\sqrt3}{2}$, $\pi/6$ gives $\frac1{2\sqrt3}$, and $\pi/12$ gives $\frac{(\sqrt3-1)^4}{8}$. Trap: the height is $HF$ (on the circle), not $HE$.")
fix(P+"2022 Paper 1 Q35",r"(I) $\Delta U=mL-P\Delta V=2250-10^5(10^{-3}-10^{-6})\approx2150$ J, about 2 kJ. (II) $\Delta U=nC_v\Delta T=0.2\cdot\frac52\cdot8\cdot1000=4$ kJ. (III) $P_2=2\cdot8^{5/3}=64$ kPa, so $\Delta U=\frac{P_2V_2-P_1V_1}{\gamma-1}=\frac{2667-667}{2/3}=3$ kJ. (IV) With vibration, $C_v=\frac72R$ and $C_p=\frac92R$, so $\Delta U=\frac79\cdot9=7$ kJ. So I-P, II-R, III-T, IV-Q.",
    stem=items[P+"2022 Paper 1 Q35"]['stem'].replace('correct?\\','correct?'))
fix(P+"2022 Paper 1 Q52",r"$\mathrm{BaO_2+H_2SO_4\to BaSO_4+H_2O_2}$ (Q). $\mathrm{MgCl_2+Ca(OH)_2\to Mg(OH)_2+CaCl_2}$ (R). $\mathrm{BaO_2+2HCl\to BaCl_2+H_2O_2}$ (S). $\mathrm{Mg(HCO_3)_2+2Ca(OH)_2\to2CaCO_3+Mg(OH)_2+2H_2O}$ (P). So I-Q, II-R, III-S, IV-P. Trap: (T) also gives $\mathrm{CaCO_3}$, but only option D fits the other matches.",
    stem=items[P+"2022 Paper 1 Q52"]['stem'].replace('option\\','option'))
fix(P+"2022 Paper 1 Q53",r"(I) $\mathrm{Cr^{2+}}$, $d^4$, with strong-field $\mathrm{CN^-}$ is low spin: R, T. (II) $\mathrm{Ru^{4+}}$ is $4d^4$ and low spin, $t_{2g}^4$: P, S. (III) $\mathrm{Cr^{2+}}$, $d^4$, high spin with 4 unpaired electrons, $\mu=\sqrt{24}=4.9$ BM: Q, T. (IV) $\mathrm{Fe^{2+}}$, $d^6$, high spin $t_{2g}^4e_g^2$ with 4 unpaired electrons: P, Q. Trap: 4d/5d metals are low spin even with weak-field $\mathrm{Cl^-}$.",
    stem=items[P+"2022 Paper 1 Q53"]['stem'].replace(r'(Q) $\mu$ (spin-only $=4.9 \mathrm{BM}$',r'(Q) $\mu$ (spin-only) $=4.9 \mathrm{~BM}$').replace(r'$t_{2 \mathrm{~g}}$',r'$t_{2g}$'))
ok(P+"2022 Paper 1 Q54",r"Aniline contains N (Prussian blue test, P) and gives a white tribromo precipitate with bromine water (S). o-Cresol is a phenol, so it gives violet with neutral $\mathrm{FeCl_3}$ (T). Cysteine contains S (nitroprusside test, Q) and has $-\mathrm{COOH}$, which releases $\mathrm{CO_2}$ with $\mathrm{NaHCO_3}$ (R). Caprolactam contains N only (P). Trap: phenols are too weakly acidic to cause effervescence with bicarbonate.")
ok(P+"2022 Paper 2 Q15",r"With at least one red and one blue from a box, the number of ways to take 2, 3, 4, 5 balls from it is $6, 9, 5, 1$. Each box gives at least 2 balls, so the 2 extra balls either both come from one box ($4\times5\times6^3=4320$) or one each from two boxes ($\binom42\times9^2\times6^2=17496$). Total $=21816$.")
ok(P+"2022 Paper 2 Q16",r"Write $M=I+N$ with $N=\frac32\begin{pmatrix}1&1\\-1&-1\end{pmatrix}$, so $N^2=0$. Then $M^n=I+nN$. For $n=2022$, $nN$ has entries $\pm3033$, giving $M^{2022}=\begin{pmatrix}3034&3033\\-3033&-3032\end{pmatrix}$. Trap: check the sign pattern; it must match $M$'s structure.")
ok(P+"2022 Paper 2 Q17",r"$P(\text{green})=\frac{8}{16}\cdot\frac{15}{48}+\frac3{16}\cdot\frac{12}{16}+\frac5{16}=\frac{39}{64}$; the last term counts $b$ itself being green. White is possible only through Box-IV, which also requires $b$ green: $P=\frac5{16}\cdot\frac6{32}=\frac{15}{256}$. So the conditional probability is $\frac{15/256}{39/64}=\frac5{52}$. Trap: $\frac{15}{256}$ is the joint probability, not the conditional one.")
ok(P+"2022 Paper 2 Q18",r"The $k$-th fraction is $\frac{16k+(9-4k)n-3n^2}{4kn+3n^2}=-1+\frac{16k+9n}{4kn+3n^2}$ for $k=1,\dots,n$, since the last term has $k=n$. The $-1$'s cancel the leading $n$, so $f(n)=\frac1n\sum_{k=1}^n\frac{16(k/n)+9}{4(k/n)+3}\to\int_0^1\frac{16x+9}{4x+3}dx$. This equals $\int_0^1\left(4-\frac3{4x+3}\right)dx=4-\frac34\ln\frac73$.")
fix(P+"2022 Paper 2 Q34",r"By Einstein's equation, $\frac{hc}{\lambda}-\phi=6.0$ eV and $\frac{hc}{4\lambda}-\phi=0.6$ eV. Subtracting gives $\frac34\frac{hc}{\lambda}=5.4$, so $\frac{hc}{\lambda}=7.2$ eV and $\phi=1.2$ eV. Then $\lambda=\frac{1.24\times10^{-6}}{7.2}=1.72\times10^{-7}$ m. Trap: intensity does not affect the stopping potential.",
    stem=items[P+"2022 Paper 2 Q34"]['stem'].replace(r'$\frac{h c}{e}=1.24 \times$ $10^{-6} \mathrm{~J} \mathrm{mC}^{-1}$',r'$\frac{h c}{e}=1.24 \times 10^{-6} \mathrm{~J~m~C}^{-1}$'))
fix(P+"2022 Paper 2 Q35",r"One rotation moves the screw 2 divisions, i.e. $1.0$ mm, so the least count is $1.0/100=0.01$ mm. The zero error is $+4\times0.01=0.04$ mm. Readings: $2.0+0.20-0.04=2.16$ mm and $2.0+0.16-0.04=2.12$ mm, with mean $d=2.14\pm0.02$ mm. Area $=\pi(d/2)^2=\pi(1.07)^2\approx\pi(1.14\pm0.02)$ mm$^2$, since $\Delta(r^2)=2r\Delta r$. Trap: taking the least count as $0.005$ mm from the 0.5 mm pitch.",
    stem="Area of the cross-section of a wire is measured using a screw gauge. The pitch of the main scale is $0.5 \\mathrm{~mm}$. The circular scale has 100 divisions and for one full rotation of the circular scale, the main scale shifts by two divisions. The measured readings are listed below.\n- Two arms of gauge touching each other without wire: main scale reading 0 division, circular scale reading 4 divisions\n- Attempt-1, with wire: main scale reading 4 divisions, circular scale reading 20 divisions\n- Attempt-2, with wire: main scale reading 4 divisions, circular scale reading 16 divisions\nWhat are the diameter and cross-sectional area of the wire measured using the screw gauge?")
ok(P+"2022 Paper 2 Q51",r"Per fcc cell there are 4 lattice atoms and 4 atoms in alternate tetrahedral voids, 8 in total. An atom in a tetrahedral void touches a corner atom along the body diagonal: $2r=\frac{\sqrt3a}{4}$, so $r=\frac{\sqrt3a}{8}$. Packing efficiency $=\frac{8\cdot\frac43\pi r^3}{a^3}=\frac{\sqrt3\pi}{16}\approx0.34$, i.e. about 35%. Trap: the usual fcc relation $4r=\sqrt2a$ no longer holds.")
ok(P+"2022 Paper 2 Q52",r"$\mathrm{2HClO_3+2HCl\to2ClO_2+Cl_2+2H_2O}$; $\mathrm{ClO_2}$ has an odd electron, so it is the paramagnetic gas. Ozone oxidises it: $\mathrm{2ClO_2+2O_3\to Cl_2O_6+2O_2}$. Trap: $\mathrm{Cl_2}$ is diamagnetic.")
ok(P+"2022 Paper 2 Q53",r"$\mathrm{Pb(NO_3)_2+2NaCl\to PbCl_2\downarrow}$. In excess HCl, chloride complexes the lead, $\mathrm{PbCl_2+2Cl^-\to[PbCl_4]^{2-}}$, which is soluble. Trap: Pb(IV) species such as $\mathrm{[PbCl_6]^{2-}}$ need an oxidant.")
ok(P+"2023 Paper 1 Q4",r"For $x\in[\frac1{n+1},\frac1n)$, $f(x)=\sqrt n$, so $f(x)\sqrt x\to1$ as $x\to0$. The lower bound is $\int_{x^2}^x\sqrt{\frac{1-t}{t}}dt\approx2\sqrt x-2x$ and the upper bound is $2\sqrt x$, so $g(x)/\sqrt x\to2$ by squeeze. Hence $f(x)g(x)=f(x)\sqrt x\cdot\frac{g(x)}{\sqrt x}\to2$.")
ok(P+"2023 Paper 1 Q5",r"Take $\ell_2$ through $(0,0,0)$ with direction $(1,1,1)$, and the face diagonal $\ell_1$ from $(1,0,1)$ to $(1,1,0)$, direction $(0,1,-1)$; the two lines are skew. The common normal is $(1,1,1)\times(0,1,-1)=(-2,1,1)$, so $d=\frac{|(1,0,1)\cdot(-2,1,1)|}{\sqrt6}=\frac1{\sqrt6}$. Face diagonals that meet the main diagonal give $0$, and by symmetry every skew pair gives $\frac1{\sqrt6}$, so the maximum is $\frac1{\sqrt6}$.")
ok(P+"2023 Paper 1 Q6",r"$y^2<5x$ forces $x\ge1$. The ellipse then allows $x=1$, $|y|\le2$ (5 points) and $x=2$, $|y|\le3$ (7 points): $|X|=12$, giving $\binom{12}{3}=220$ triples. Area $=\frac12|\det|$ is a positive integer exactly when the determinant is a nonzero even number. Counting gives 73 such triples, so the probability is $\frac{73}{220}$. Trap: collinear triples (area 0) must be excluded.")
ok(P+"2023 Paper 1 Q7",r"Let $P=(at^2,2at)$. The normal has slope $-t$, so $m=-t>0$, and it meets the $x$-axis at $Q=(2a+at^2,0)$. With $F=(a,0)$, area $=\frac12\cdot a(1+t^2)\cdot2a|t|=a^2m(1+m^2)=120$. Then $a=2$, $m=3$ gives $4\cdot3\cdot10=120$, so $(a,m)=(2,3)$.")
fix(P+"2023 Paper 1 Q14",r"$\det=7\alpha-2\beta-3$, which vanishes iff $\beta=\frac12(7\alpha-3)$. In that case, $-\frac32E_1+\frac72E_2$ reproduces the LHS of $E_3$ with RHS $28$. So $\gamma=28$ gives infinitely many solutions and $\gamma\ne28$ gives none. If $\beta\ne\frac12(7\alpha-3)$, the solution is unique. For $\alpha=1$, $\gamma=28$, the point $(11,-2,0)$ satisfies all three equations ($11-4=7$, $11=11$, $22+6=28$). So P-3, Q-2, R-1, S-4.")
fix(P+"2023 Paper 1 Q15",r"$N=20$ and $\sum f_ix_i=120$, so the mean is $6$. Sorted cumulative frequencies are 3:5, 4:9, 5:13, so the 10th and 11th values are 5 and the median is 5. MD about the mean $=\frac{15+8+4+4+8+15}{20}=2.7$; MD about the median $=\frac{10+4+0+6+10+18}{20}=2.4$. So P-3, Q-2, R-4, S-5. Trap: sort the $x_i$ before finding the median.",
    stem="Consider the given data with frequency distribution\n$$\\begin{array}{ccccccc} x_{i} & 3 & 8 & 11 & 10 & 5 & 4 \\\\ f_{i} & 5 & 2 & 3 & 2 & 4 & 4 \\end{array}$$\n"+items[P+"2023 Paper 1 Q15"]['stem'].split('$$',2)[2])
fix(P+"2023 Paper 1 Q16",r"$d(H)>0$ only if $H$ is parallel to $\ell_2$, so the normal is $(1,1,1)\times(1,0,1)=(1,0,-1)$ and $H_0: x-z=0$. Then $d(H_0)=\frac{|0-(-1)|}{\sqrt2}=\frac1{\sqrt2}$, using $(0,1,-1)\in\ell_2$. The point $(0,1,2)$ is at distance $\frac2{\sqrt2}=\sqrt2$, and the origin is at $0$. The planes $y=z$, $x=1$, $x=z$ meet at $(1,1,1)$, at distance $\sqrt3$ from the origin. So P-5, Q-4, R-3, S-1.")
fix(P+"2023 Paper 1 Q17",r"Let $z=x+iy$. The imaginary part gives $4xy-4y=0$, so $x=1$ (since $y\ne0$). The real part gives $r^3+2(1-y^2)+4-8=0$; with $y^2=r^2-1$, this becomes $r^3-2r^2=0$, so $r=2$ and $y^2=3$. Then $|z|^2=4$, $|z-\bar z|^2=4y^2=12$, $|z|^2+|z+\bar z|^2=4+4=8$, $|z+1|^2=4+3=7$. So P-2, Q-1, R-3, S-5.",
    stem=items[P+"2023 Paper 1 Q17"]['stem'].replace('Z','z'))
ok(P+"2023 Paper 1 Q21",r"$I=\frac{ML^2}{3}=\frac{0.04}{3}$ kg m$^2$. Angular momentum about the pivot: $mv_0\frac L2=-mv\frac L2+I\omega$, i.e. $0.05=-0.01v+0.0133\omega$. Kinetic energy: $mv_0^2=mv^2+I\omega^2$. Solving gives $v=4.30$ m s$^{-1}$ and $\omega=6.98$ rad s$^{-1}$. Trap: linear momentum is not conserved, because the pivot exerts an impulse.")
ok(P+"2023 Paper 1 Q23",r"Adiabatic: $T_AV_0^{\gamma-1}=T_f(5V_0)^{\gamma-1}$, so $T_A=5^{\gamma-1}T_f$. Isothermal: $T_B=T_f$. Hence $T_A/T_B=5^{\gamma-1}$. Note that $T_A>T_f$, since adiabatic expansion cools the gas.")
ok(P+"2023 Paper 1 Q24",r"$g\propto\frac1{(R+h)^2}$, so $\frac{g_P}{g_Q}=\frac{(R+h_Q)^2}{(4R/3)^2}=\frac{36}{25}$. This gives $R+h_Q=\frac65\cdot\frac{4R}{3}=\frac{8R}{5}$, so $h_Q=\frac{3R}{5}$.")
fix(P+"2023 Paper 1 Q31",r"Each $\alpha$ lowers $A$ by 4 and $Z$ by 2; $\beta^-$ raises $Z$ by 1 and $\beta^+$ lowers it by 1. P: $\Delta A=-4$, $\Delta Z=-1$, so one $\alpha$ and one $\beta^-$ (4). Q: $\Delta Z=0$, so one $\alpha$ and two $\beta^-$ (3). R: $\Delta Z=+1$, so one $\alpha$ and three $\beta^-$ (2). S: $\Delta Z=-3$, so one $\alpha$ and one $\beta^+$ (1).")
fix(P+"2023 Paper 1 Q33",r"$C=\frac1{\omega_0^2L}=2\times10^{-9}$ F. At $\omega=8\times10^4$: $X_L=4000\,\Omega$ and $X_C=6250\,\Omega$, so $|X|=2250\,\Omega$. $Z=20R$ gives $R=2250/\sqrt{399}\approx112.6\,\Omega$. Then $I_0=45/R\approx0.4$ A $=400$ mA, $Q=\omega_0L/R\approx44.4$, bandwidth $=R/L\approx2250$ rad s$^{-1}$, and peak power $=I_0^2R=V_0I_0=18$ W. So P-3, Q-1, R-4, S-2.")
ok(P+"2023 Paper 1 Q39",r"For a weak acid, $\alpha=\Lambda_m/\Lambda_m^o$ and $K_a=\frac{c\alpha^2}{1-\alpha}$. Rearranging (Ostwald's law) gives $\frac1{\Lambda_m}=\frac1{\Lambda_m^o}+\frac{c\Lambda_m}{K_a(\Lambda_m^o)^2}$. So $P=\frac1{\Lambda_m^o}$, $S=\frac1{K_a(\Lambda_m^o)^2}$, and $P/S=K_a\Lambda_m^o$.")
ok(P+"2023 Paper 1 Q40",r"For MX of a weak acid, $s^2=K_{sp}\left(1+\frac{[\mathrm H^+]}{K_a}\right)$. At pH 7 the hydrolysis term is negligible, so $K_{sp}=10^{-8}$. At pH 2: $10^{-6}=10^{-8}(1+10^{-2}/K_a)$, so $10^{-2}/K_a\approx99$, $K_a\approx10^{-4}$, and $pK_a=4$.")
fix(P+"2023 Paper 1 Q48",r"$\mathrm{P_2O_3+3H_2O\to2H_3PO_3}$ (2). $\mathrm{P_4+3NaOH+3H_2O\to PH_3+3NaH_2PO_2}$ (3). $\mathrm{PCl_5+CH_3COOH\to CH_3COCl+POCl_3+HCl}$ (4). $\mathrm{H_3PO_2+2H_2O+4AgNO_3\to4Ag+H_3PO_4+4HNO_3}$ (5). Trap: $\mathrm{PCl_5}$ chlorinates the acid; it does not form a P-ester.")
fix(P+"2023 Paper 1 Q49",r"P: $\mathrm{Co^{3+}}$ ($d^6$) with strong-field $\mathrm{NH_3}$ gives $t_{2g}^6e_g^0$ (3). Q: $\mathrm{Mn^{2+}}$ ($d^5$) high spin, octahedral, gives $t_{2g}^3e_g^2$ (2). R: $e^2t_2^3$ is a tetrahedral $d^5$ ion, $\mathrm{[FeCl_4]^-}$ with $\mathrm{Fe^{3+}}$ (4). S: $\mathrm{Fe^{2+}}$ ($d^6$) high spin in water gives $t_{2g}^4e_g^2$ (1). Trap: $\mathrm{[CoCl_4]^{2-}}$ is $d^7$, i.e. $e^4t_2^3$.")
fix(P+"2023 Paper 1 Q51",r"Benzene with $\mathrm{CH_3Cl/AlCl_3}$ gives toluene, the Etard substrate (P-3). Aniline with $\mathrm{NaNO_2/HCl}$ gives a diazonium salt, the Gattermann substrate (Q-4). Phenol with Zn dust gives benzene, the Gattermann-Koch substrate (R-5). Toluene with $\mathrm{KMnO_4}$ then $\mathrm{SOCl_2}$ gives benzoyl chloride, the Rosenmund substrate (S-2). Trap: Clemmensen reduction of acetophenone gives ethylbenzene, which matches none of these.")
ok(P+"2023 Paper 2 Q1",r"Differentiate: $3f=f+xf'-x^2$, so $xf'-2f=x^2$, i.e. $\left(\frac f{x^2}\right)'=\frac1x$. Hence $\frac f{x^2}=\ln x+c$, and $f(1)=\frac13$ gives $c=\frac13$. So $f(e)=e^2\left(1+\frac13\right)=\frac{4e^2}{3}$.")
ok(P+"2023 Paper 2 Q2",r"Let $p=\frac13$, $q=\frac23$, and let $a$ be the probability of finishing with heads given the last toss was H. Then $a=p+q\cdot pa$, so $a=\frac p{1-pq}=\frac37$. Starting fresh, $P=pa+q(pa)=pa(1+q)=\frac13\cdot\frac37\cdot\frac53=\frac5{21}$. Trap: answering $p^2/(p^2+q^2)$ ignores the alternating structure.")
ok(P+"2023 Paper 2 Q3",r"Let $u=\frac{6y}{9-y^2}$. For $0<y<3$, $u>0$ and $\cot^{-1}(1/u)=\tan^{-1}u$, so $\tan^{-1}u=\pi/3$. Then $y^2+2\sqrt3y-9=0$ gives $y=\sqrt3$. For $-3<y<0$, $u<0$ and $\cot^{-1}(1/u)=\pi+\tan^{-1}u$, so $\tan^{-1}u=-\pi/6$. Then $y^2-6\sqrt3y-9=0$ gives $y=3\sqrt3-6$. Sum $=4\sqrt3-6$. Trap: missing the $\pi$ shift for negative arguments.")
ok(P+"2023 Paper 2 Q4",r"$\frac{\vec b+2\vec d}{3}=\left(\frac73,\frac83,\frac53\right)$, and $\frac{5\vec c+4\vec a}{9}=\frac{(17+4,16+8,35-20)}{9}=\left(\frac73,\frac83,\frac53\right)$. They match, so the point divides $PR$ internally in ratio $5:4$. It also lies on $QS$, so the four points are coplanar, and $|\vec b\times\vec d|^2=9^2+3^2+(-9)^2=171\ne95$.")
ok(P+"2023 Paper 2 Q19",r"$[Y]=ML^{-1}T^{-2}$, $[c]=LT^{-1}$, $[h]=ML^2T^{-1}$, $[G]=M^{-1}L^3T^{-2}$. Matching powers: M: $\beta-\gamma=1$; L: $\alpha+2\beta+3\gamma=-1$; T: $-\alpha-\beta-2\gamma=-2$. Solving gives $\alpha=7$, $\beta=-1$, $\gamma=-2$.")
ok(P+"2023 Paper 2 Q20",r"$a_x=\frac{dv_x}{dt}=\alpha\dot y=\alpha\cdot2\alpha x=2\alpha^2x$ and $a_y=2\alpha\dot x=2\alpha\cdot\alpha y=2\alpha^2y$. So $\vec F=m\vec a=2m\alpha^2(x\hat x+y\hat y)$. Trap: $\vec v$ is a velocity field, so differentiate along the motion; do not multiply $\vec v$ by $\alpha$.")
ok(P+"2023 Paper 2 Q21",r"$\gamma=1+\frac2n$ and $v=\sqrt{\gamma RT/M}$. At fixed $T$, fewer degrees of freedom means larger $\gamma$ and faster sound, so $v_5>v_7$. $U_n=\frac n2RT$ grows with $n$, so $U_5<U_7$. Option C satisfies both conditions.")
ok(P+"2023 Paper 2 Q36",r"(I) True: lyophobic sols need special methods. (II) True: an emulsion is liquid in liquid. (III) False: micelles form only above the CMC and above the Kraft temperature. (IV) False: the Tyndall effect requires a refractive-index difference. So (I) and (II).")
missing=set(items)-set(E); print("missing",missing, "extra", set(E)-set(items))
json.dump(E,open('../jb_batch2.result.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
r=json.load(open('../jb_batch2.result.json',encoding='utf-8'))
from collections import Counter; print(len(r),Counter(v['verdict'] for v in r.values()))
