import json, os
os.chdir('D:/PersonalProjects/Revanth/bitsat-mock/.harvest/verify')
items={x['ref']:x for x in json.load(open('jb_batch1.json',encoding='utf-8'))}
R={}
def ok(r,e): R[r]={"verdict":"ok","explanation":e}
def fix(r,e,stem=None,opts=None):
    it=items[r]; R[r]={"verdict":"fix","explanation":e,"stem":stem or it['stem'],"options":opts or dict(it['options'])}
P=lambda y:"JEE Adv "+y
s=items[P("2016 Paper 1 Q2")]['stem']
old=r"\left(g=10 \mathrm{~ms} \mathrm{~s}^{2}\right)"
assert old in s
s=s.replace(old, r"\left(g=10 \mathrm{~m\,s^{-2}}\right)")
fix(P("2016 Paper 1 Q2"), r"Floor normal $R$ equals wall reaction $N$ (given). $N\perp$ stick has vertical part $N\sin30^\circ$, so $R+N/2=mg=16$ gives $N=32/3$ N and $f=N\cos30^\circ=16\sqrt3/3$ N. Torque about the bottom: $N\,\frac{h}{\cos30^\circ}=mg\frac{l}{2}\sin30^\circ=4l$, so $h/l=\frac{4\cos30^\circ}{N}=\frac{3\sqrt3}{16}$. Trap: the wall force is not horizontal here, since it acts perpendicular to the stick at the wall's edge.", stem=s)
ok(P("2016 Paper 2 Q1"), r"$BE_N-BE_O=(m_n-m_H+m_O-m_N)c^2=(0.000840+0.002956)(931.5)\approx3.54$ MeV. This equals the Coulomb energy difference $\frac35\frac{1.44}{R}[8\cdot7-7\cdot6]=\frac{12.096}{R}$ MeV fm. Hence $R=12.096/3.54\approx3.42$ fm. Trap: use $Z(Z-1)$, not $Z^2$.")
ok(P("2016 Paper 2 Q2"), r"Activity must fall by a factor $64=2^6$, i.e. 6 half-lives. Time $=6\times18=108$ days.")
ok(P("2016 Paper 2 Q3"), r"$P^3V^5=$ const means $\gamma=5/3$, so $\Delta U=\frac{P_fV_f-P_iV_i}{\gamma-1}=\frac32(25-100)=-112.5$ J. Work in the two-step path is only in the isobaric step: $W=P_i(V_f-V_i)=10^5\times7\times10^{-3}=700$ J. $Q=\Delta U+W\approx588$ J. Trap: $\Delta U$ depends only on end states, so compute it once.")
ok(P("2016 Paper 2 Q4"), r"Same heat current through equal-length wires (equal area): $2k(T-10)=k(400-T)$, so junction $T=140^\circ$C. The temperature in PQ varies linearly from 10 to 140, so the average rise is $65^\circ$C. $\Delta L=1\times1.2\times10^{-5}\times65=7.8\times10^{-4}$ m $=0.78$ mm. Trap: using the full $130^\circ$C rise gives the wrong value 1.56 mm.")
s=items[P("2016 Paper 2 Q19")]['stem']
for a,b in [(r"E_{\mathrm{M}^{4} / \mathrm{M}^{2+}}^{0}", r"E_{\mathrm{M}^{4+} / \mathrm{M}^{2+}}^{0}"),(r"\left[M^{4+}(aq)\right]", r"\left[\mathrm{M}^{4+}(aq)\right]"),(r"\operatorname{Pt}(s)", r"\mathrm{Pt}(s)")]:
    assert a in s, a; s=s.replace(a,b)
fix(P("2016 Paper 2 Q19"), r"The cell reaction is $\mathrm{H_2+M^{4+}\to2H^++M^{2+}}$ with $n=2$ and $E^\circ_{cell}=0.151$ V. Nernst: $0.092=0.151-\frac{0.059}{2}\log\frac{[\mathrm{M^{2+}}]}{[\mathrm{M^{4+}}]}$, so $\log(\text{ratio})=2$ and $x=2$. Trap: using $n=1$ gives the wrong value $x=1$.", stem=s)
ok(P("2016 Paper 2 Q22"), r"$[\mathrm{Ni(NH_3)_6}]^{2+}$ is octahedral ($sp^3d^2$). $[\mathrm{Pt(NH_3)_4}]^{2+}$ is square planar because $5d^8$ gives a large crystal-field splitting ($dsp^2$). $[\mathrm{Zn(NH_3)_4}]^{2+}$ is tetrahedral because $d^{10}$ gives no CFSE preference ($sp^3$).")
ok(P("2016 Paper 2 Q37"), r"Write $P=I+N$ with $N$ nilpotent ($N^3=0$). Then $P^{n}=I+nN+\binom n2N^2$, giving $(P^n)_{21}=4n$, $(P^n)_{32}=4n$ and $(P^n)_{31}=16n+16\binom n2$. For $n=50$: $q_{21}=q_{32}=200$ and $q_{31}=800+19600=20400$. Ratio $=\frac{20600}{200}=103$.")
ok(P("2016 Paper 2 Q38"), r"The $b_i$ form a GP with ratio 2, and the $a_i$ form an AP sharing the same 1st and 51st terms. Between these terms the GP lies below the chord (convexity), so $a_i\ge b_i$ for $i\le51$ and $s>t$. Beyond term 51 the GP outgrows the AP: $a_{101}=2a_{51}-a_1=b_1(2^{51}-1)<b_1 2^{100}=b_{101}$.")
ok(P("2016 Paper 2 Q40"), r"Add the integral to itself with $x\to-x$. Since $\frac1{1+e^x}+\frac1{1+e^{-x}}=1$, this gives $2I=\int_{-\pi/2}^{\pi/2}x^2\cos x\,dx$, so $I=\int_0^{\pi/2}x^2\cos x\,dx$. Integrating by parts: $[x^2\sin x+2x\cos x-2\sin x]_0^{\pi/2}=\frac{\pi^2}{4}-2$.")
ok(P("2017 Paper 2 Q1"), r"Constant mass gives $\rho R^3=$ const, so $\frac1\rho\frac{d\rho}{dt}=-\frac3R\frac{dR}{dt}$. Setting this constant gives $v=\frac{dR}{dt}\propto R$.")
ok(P("2017 Paper 2 Q3"), r"$\lambda_d=h/\sqrt{2mK}$ with $K=\frac{hc}{\lambda}-\phi_0$, so $\lambda_d^{-2}\propto\frac{hc}{\lambda}-\phi_0$. Differentiating: $-2\lambda_d^{-3}d\lambda_d\propto-\frac{hc}{\lambda^2}d\lambda$. Therefore $\frac{\Delta\lambda_d}{\Delta\lambda}\propto\frac{\lambda_d^3}{\lambda^2}$.")
ok(P("2017 Paper 2 Q6"), r"Energy needed per unit mass is $\frac{GM_e}{R_e}+\frac{GM_s}{r}=\frac{GM_e}{R_e}\left(1+\frac{3\times10^5}{2.5\times10^4}\right)=13\frac{GM_e}{R_e}$. Hence $v_S=\sqrt{13}\,v_e\approx3.6\times11.2\approx40$ km/s, closest to 42 km/s. Trap: adding the two escape speeds directly is wrong; their squares add.")
ok(P("2017 Paper 2 Q7"), r"$T=\sqrt{2L/g}+L/v=2+\frac1{15}$ s. $\frac{dT}{dL}=\frac1{\sqrt{2gL}}+\frac1v=\frac1{20}+\frac1{300}=\frac{16}{300}$. So $\delta L=\frac{0.01\times300}{16}\approx0.19$ m and $\delta L/L\approx0.94\%\approx1\%$.")
ok(P("2017 Paper 2 Q20"), r"$E=1.1-\frac{2.303RT}{2F}\log\frac{[\mathrm{Zn^{2+}}]}{[\mathrm{Cu^{2+}}]}=1.1-\frac{2.303RT}{2F}$. $\Delta G=-nFE=-2F\,E=2.303RT-2.2F$. Trap: $n=2$ multiplies both terms.")
ok(P("2017 Paper 2 Q22"), r"Zinc is amphoteric: $\mathrm{Zn+2NaOH+2H_2O\to Na_2[Zn(OH)_4]+H_2}$. Concentrated $\mathrm{HNO_3}$ gives $\mathrm{NO_2}$ with Cu and passivates Fe. Au with cyanide and air forms $[\mathrm{Au(CN)_2}]^-$ and no $\mathrm{H_2}$.")
ok(P("2017 Paper 2 Q23"), r"Oxidation states of P: $\mathrm{H_3PO_2}=+1$, $\mathrm{H_3PO_3}=+3$, $\mathrm{H_4P_2O_6}=+4$, $\mathrm{H_3PO_4}=+5$. Order: $\mathrm{H_3PO_4>H_4P_2O_6>H_3PO_3>H_3PO_2}$.")
o=dict(items[P("2017 Paper 2 Q37")]['options']); o['C']="$14 x+2 y+15 z=31$"
fix(P("2017 Paper 2 Q37"), r"The required normal is perpendicular to both given normals: $(2,1,-2)\times(3,-6,-2)=(-14,-2,-15)$. The plane is $14x+2y+15z=d$, and through $(1,1,1)$ we get $d=31$.", opts=o)
ok(P("2017 Paper 2 Q38"), r"From the first equality: $\vec p\cdot\vec q-\vec q\cdot\vec s=\vec r\cdot\vec p-\vec r\cdot\vec s$, i.e. $(\vec p-\vec s)\cdot(\vec q-\vec r)=0$, so $SP\perp QR$. Similarly $SQ\perp RP$ and $SR\perp PQ$. So $S$ is the orthocentre.")
ok(P("2017 Paper 2 Q39"), r"Let $u=\sqrt{4+\sqrt{9+\sqrt x}}$. Then $du=\frac{dx}{8\sqrt x\sqrt{9+\sqrt x}\,u}$, which is exactly the right side, so $y=u+C$. $y(0)=\sqrt{4+3}=\sqrt7$ gives $C=0$. Then $y(256)=\sqrt{4+\sqrt{9+16}}=3$.")
ok(P("2017 Paper 2 Q40"), r"By MVT on $[\frac12,1]$ there is $c$ with $f'(c)=\frac{1-1/2}{1/2}=1$. Since $f''>0$, $f'$ is strictly increasing, so $f'(1)>f'(c)=1$.")
ok(P("2017 Paper 2 Q41"), r"$\mathrm{tr}(M^TM)$ is the sum of squares of all 9 entries. With entries in $\{0,1,2\}$, a total of 5 needs either five 1's ($\binom95=126$ ways) or one 2 and one 1 ($9\times8=72$ ways). Total $=198$.")
ok(P("2017 Paper 2 Q42"), r"Each 5-element subset has at least one odd element, because there are only 4 evens. So the sum counts all 5-subsets: $\binom95=126$.")
ok(P("2017 Paper 2 Q43"), r"Total solutions: $\binom{12}{2}=66$. For $z=0,2,\dots,10$ the counts of $(x,y)$ are $11,9,7,5,3,1$, totalling 36. Probability $=\frac{36}{66}=\frac6{11}$.")
ok(P("2019 Paper 1 Q1"), r"For circular orbits, $\frac{mv^2}{r}=\frac{GM(r)m}{r^2}$, so $2K=\frac{GM(r)m}{r}$ and $M(r)=\frac{2Kr}{Gm}$. Then $4\pi r^2\rho=\frac{dM}{dr}=\frac{2K}{Gm}$, so $\rho=\frac{K}{2\pi r^2Gm}$ and $n=\frac{K}{2\pi r^2m^2G}$.")
ok(P("2019 Paper 1 Q2"), r"Treat the hole as the full shell plus a small patch of charge $-\alpha Q$, where $kQ/R=V_0$. At the centre: $V=V_0(1-\alpha)$. At $R/2$ toward the hole, the patch is $R/2$ away, so $V=V_0-2\alpha V_0$. Ratio $=\frac{1-\alpha}{1-2\alpha}$. Trap: the field at the centre rises from 0 to $\alpha V_0/R$; it is not reduced.")
ok(P("2019 Paper 1 Q3"), r"$\frac{dT}{dt}=\frac{T_0\beta}{4}t^{-3/4}$, so $C=\frac{P}{dT/dt}=\frac{4P\,t^{3/4}}{T_0\beta}$. From $t=\left(\frac{T-T_0}{\beta T_0}\right)^4$ we get $t^{3/4}=\frac{(T-T_0)^3}{\beta^3T_0^3}$. Hence $C=\frac{4P(T-T_0)^3}{\beta^4T_0^4}$.")
ok(P("2019 Paper 1 Q4"), r"Total decay constant $\lambda=5\times10^{-10}$ per year. $\frac{N_0-N}{N}=e^{\lambda t}-1=99$ gives $e^{\lambda t}=100$. So $\lambda t=2\ln10=4.6$ and $t=9.2\times10^9$ yr. Trap: in parallel decay the decay constants add.")
R[P("2019 Paper 1 Q19")]={"verdict":"drop","reason":"Contested key: standard texts attribute the green Cr borax bead to Cr(BO2)3 (option A), but the official key gives C (Cr2O3). Not confident enough to write an explanation that backs the key."}
ok(P("2019 Paper 1 Q20"), r"Calamine is $\mathrm{ZnCO_3}$, malachite is $\mathrm{CuCO_3\cdot Cu(OH)_2}$, magnetite is $\mathrm{Fe_3O_4}$, and cryolite is $\mathrm{Na_3AlF_6}$. Trap: $\mathrm{Fe_2O_3}$ is haematite, not magnetite.")
s=items[P("2019 Paper 1 Q37")]['stem']
for a,b in [("complex numbers $Z$","complex numbers $z$"),("complex number $Z_{0}$","complex number $z_{0}$"),(r"\left|Z_{0}-1\right|",r"\left|z_{0}-1\right|"),(r"{Z_{0}-\overline{z_{0}}+2 i}",r"{z_{0}-\overline{z_{0}}+2 i}")]:
    assert a in s, a; s=s.replace(a,b)
fix(P("2019 Paper 1 Q37"), r"$S$ is the region outside the circle with centre $2-i$ and radius $\sqrt5$, and $1$ lies inside that circle. So $|z-1|$ is minimised at the boundary point in the direction from $2-i$ through $1$: $z_0=x+iy$ with $x=2-\sqrt{5/2}<2$ and $y+1=\sqrt{5/2}>0$. The expression is $\frac{4-2x}{2i(y+1)}=-i\cdot(\text{positive})$, so its argument is $-\frac\pi2$.", stem=s)
ok(P("2019 Paper 1 Q39"), r"The midpoint $M=(-\frac35,1-\frac{3m}5)$ is the foot of the perpendicular from the centre $(3,-2)$, so the slope of $CM$ is $-1/m$. This gives $m(15-3m)=18$, i.e. $m^2-5m+6=0$, so $m=2$ or $3$. Both values give a line within distance 5 of the centre, so they are valid, and $2\le m<4$.")
ok(P("2019 Paper 1 Q40"), r"The intended bounded region is in the first quadrant. The curves $xy=8$ and $y=x^2$ meet at $(2,4)$. For $1\le y\le4$, $x$ runs from $\sqrt y$ to $8/y$. Area $=\int_1^4\left(\frac8y-\sqrt y\right)dy=8\ln4-\frac23(8-1)=16\ln2-\frac{14}3$.")
ok(P("2020 Paper 1 Q20"), r"Superoxide hydrolysis releases oxygen: $\mathrm{4KO_2+2H_2O\to4KOH+3O_2}$. Peroxides such as $\mathrm{Na_2O_2}$ and $\mathrm{Li_2O_2}$ give $\mathrm{H_2O_2}$ on hydrolysis, and $\mathrm{Pb_3O_4}$ does not hydrolyse to give $\mathrm{O_2}$.")
ok(P("2020 Paper 1 Q21"), r"The white chloride precipitate is $\mathrm{AgCl+PbCl_2}$. $\mathrm{PbCl_2}$ dissolves in hot water, and the solution Q gives yellow $\mathrm{PbI_2}$ with KI. The residue P, $\mathrm{AgCl}$, dissolves in $\mathrm{NH_3}$ (as $[\mathrm{Ag(NH_3)_2}]^+$) and in thiosulfate. So X = Ag and Y = Pb.")
ok(P("2020 Paper 1 Q37"), r"The expression equals $(c+d)(a^2+b^2)-(a+b)(c^2+d^2)$. Here $a+b=-20$ and $ab=-2020$, so $a^2+b^2=4440$; also $c+d=20$ and $cd=2020$, so $c^2+d^2=-3640$. Value $=20(4440)-(-20)(-3640)=88800-72800=16000$.")
ok(P("2020 Paper 1 Q38"), r"$f$ is odd. For $x>0$, $f=x(x-\sin x)$ and $f'=(x-\sin x)+x(1-\cos x)>0$, so $f$ is strictly increasing on $\mathbb R$ and therefore one-one. $f\to\pm\infty$ as $x\to\pm\infty$ and $f$ is continuous, so it is onto.")
ok(P("2020 Paper 1 Q39"), r"For $x<1$, $f=0$; for $x\ge1$, $f=e^{x-1}-e^{1-x}$. The curves $f=g$ meet where $e^{2(x-1)}=3$, i.e. $x_0=1+\frac12\ln3$. Area $=\int_0^1g\,dx+\int_1^{x_0}(g-f)\,dx=\frac12(e-e^{-1})+(2-\sqrt3)$.")
ok(P("2020 Paper 1 Q40"), r"$P=(\lambda,2\lambda)$ and the parabola's slope there is $2\lambda/y=1$. The ellipse's slope at $P$ is $-\frac{b^2x}{a^2y}=-\frac{b^2}{2a^2}$, and perpendicularity requires this to be $-1$, so $b^2=2a^2$. The major axis is along $y$, so $e=\sqrt{1-a^2/b^2}=\frac1{\sqrt2}$. Trap: the formula $1-b^2/a^2$ fails because $b>a$.")
ok(P("2020 Paper 1 Q41"), r"Equal roots need $\alpha^2=4\beta$, so $(\alpha,\beta)=(0,0)$ or $(2,1)$. $P(\alpha=0)=\frac19$ and $P(\beta=0)=\frac49$; $P(\alpha=2)=\frac49$ and $P(\beta=1)=\frac49$. Total $=\frac4{81}+\frac{16}{81}=\frac{20}{81}$.")
ok(P("2020 Paper 1 Q42"), r"Take the base from $a$ to $\frac\pi2-a$ with height $2\sin2a$, so the perimeter is $\pi-4a+4\sin2a$. Setting the derivative to zero gives $\cos2a=\frac12$, so $a=\frac\pi6$. The width is $\frac\pi6$ and the height is $\sqrt3$, so the area is $\frac{\pi\sqrt3}{6}=\frac{\pi}{2\sqrt3}$. Trap: maximising area instead of perimeter gives a different rectangle.")
ok(P("2021 Paper 1 Q4"), r"One hour is 3 half-lives, so $1000(1-\frac18)=875$ nuclei decay. 60% of them decay by alpha emission: $0.6\times875=525$.")
ok(P("2021 Paper 1 Q22"), r"$\mathrm{Cr^{3+}}$ is $d^3$ with 3 unpaired electrons: $\mu=\sqrt{15}=3.87$ BM. In $[\mathrm{CuF_6}]^{3-}$, $\mathrm{Cu^{3+}}$ is $d^8$ in an octahedral field with 2 unpaired electrons: $\mu=\sqrt8=2.84$ BM. Trap: Cu here is +3, not +2.")
ok(P("2021 Paper 1 Q37"), r"Vertex $A=(-1,0)$. The altitude from $C$ (on $x+y+1=0$) to the $x$-axis is $x=1$, so $C=(1,-2)$. The altitude from $B$ is perpendicular to the line (slope 1) and passes through $(1,1)$, so it is $y=x$, giving $B=(0,0)$. The circle $x^2+y^2+Dx+Ey=0$ through $A$ and $C$ gives $D=1$ and $E=3$.")
ok(P("2021 Paper 1 Q38"), r"For $0\le y\le\frac12$, $x$ runs from $2-y$ to $\frac94$. For $\frac12\le y\le\frac34$, $x$ runs from $3y$ to $\frac94$. Area $=\int_0^{1/2}(\frac14+y)dy+\int_{1/2}^{3/4}(\frac94-3y)dy=\frac14+\frac3{32}=\frac{11}{32}$.")
ok(P("2021 Paper 1 Q39"), r"$E_3=E_1$ requires $S_3=S_1$. For $S_1=\{1,2\}$: need $1\in S_2$ (prob $\frac36$), then $|G_2|=5$, giving $\frac12\cdot\frac1{10}=\frac1{20}$. For $S_1=\{1,3\}$: $\frac23\cdot\frac1{10}=\frac1{15}$. For $S_1=\{2,3\}$: $\frac12\cdot\frac16+\frac12\cdot\frac1{10}=\frac2{15}$. So $p=\frac{1/20}{1/20+1/15+2/15}=\frac{3}{15}=\frac15$.")
assert set(R)==set(items)
json.dump(R,open('jb_batch1.result.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
r=json.load(open('jb_batch1.result.json',encoding='utf-8'))
from collections import Counter; print(len(r),Counter(v['verdict'] for v in r.values()))
